# Generated by Django 4.0 on 2022-03-29 15:25

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='result_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobname', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('Q_P', models.CharField(max_length=20)),
                ('Q_P_S', models.TextField()),
                ('PDB', models.FileField(default=None, max_length=300, null=True, upload_to='PDB/')),
                ('DSM', models.TextField()),
                ('DMM', models.FileField(default=None, max_length=300, null=True, upload_to='DMM/')),
                ('MSF', models.FileField(default=None, max_length=300, null=True, upload_to='MSF/')),
                ('PC', models.CharField(max_length=100)),
                ('List', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=66, size=6)),
                ('Forcefield', models.CharField(max_length=100)),
                ('MLK', models.CharField(max_length=100)),
            ],
        ),
    ]
